blog/urls.py
  
from django.urls import path
from .views import (
    PostListView,
    PostListView2,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,

    CommentCreateView,
    CommentDetailView,
    # CommentUpdateView,
    # CommentDeleteView,
    comment_save,
    comment_edit,
    comment_delete,

    subscribe_post,
    unsubscribe_post,
    user_notifications,

    post_tag_save,
    tag_delete,
    #TagPostsView,
    TagPostsTemplateView,

)
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('user/<str:username>/notifications', user_notifications, name='user-notifications'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

    path('post/<int:post_id>/comments/new', CommentCreateView.as_view(), name='post-comment-create'),
    path('post/<int:post_id>/comments/new2', comment_save, name='add-comment'),

    path('comment/<int:pk>/', CommentDetailView.as_view(), name='comment-detail'),
    path('comment/<int:comment_id>/update', comment_edit, name='edit-comment'),
    #path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment-update'),
    # path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),
    path('comment/<int:comment_id>/delete', comment_delete, name='comment-delete'),

    path('post/<int:post_id>/subscribe', subscribe_post, name='post-subscription'),
    path('post/<int:post_id>/unsubscribe', unsubscribe_post, name='post-unsubscription'),

    path('post/<int:post_id>/tags/new', post_tag_save, name='post-tag-create'),
    path('tags/<int:tag_id>/delete', tag_delete, name='post-tag-delete'),
 #   path('tags/<str:tag_choice>/posts', TagPostsView.as_view(), name='tag-posts'),
    path('tags/<path:tag_choices>/posts', TagPostsTemplateView.as_view(), name='tag-posts'),

    path('poc', PostListView2.as_view(), name='blog-home'),



    path('about/', views.about, name='blog-about'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as users_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from blog.api import PostResource, UserResource, TagTypeResource
from tastypie.api import Api
from blog import api

post_resource = PostResource()
user_resource = UserResource()
tagtype_resource = TagTypeResource()


v1_api = Api(api_name ="v1")
v1_api.register(user_resource)
v1_api.register(post_resource)
v1_api.register(tagtype_resource)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('register/', users_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', users_views.profile, name='profile'),

    path('api/', include(v1_api.urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.template.defaultfilters import register
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django import template

register = template.Library()


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    anonymous = models.BooleanField("Post as Anonymous User", editable=True, default=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    is_user_subscribed = False
    is_user_subscribed_not = not is_user_subscribed

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


    # @register.tag
    # def is_subscribed_to_user(self, user):
    #     is_subscribed = self.subscriptions.filter(user__exact=user).exists()
    #     return is_subscribed


class Comment(models.Model):
    content = models.TextField()
    anonymous = models.BooleanField("Comment as Anonymous User", editable=True, default=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return self.author.username + ' (' + self.date_posted.strftime("%d %B, %Y %I:%M %p") + ') - ' + self.content

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.post.pk})



class Subscription(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='subscriptions')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subscriptions')


class Notification(models.Model):
    type = models.CharField(max_length=10, default='created')  # created, updated
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='notifications')
    subscription = models.ForeignKey(Subscription, on_delete=models.CASCADE, related_name='notifications')


# TAG_CHOICES = [
#     ('#Financial', '#Financial'),
#     ('#Political', '#Political'),
#     ('#Religious', '#Religious'),
#     ('#Offensive', '#Offensive'),
#     ('#Funny', '#Funny'),
# ]

class TagType(models.Model):
    name = models.CharField(max_length=50)


class Tag(models.Model):
    type = models.ForeignKey(TagType, on_delete=models.CASCADE, related_name='tags')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='tags')
    # tagged_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tags')

blog/views.py
from datetime import datetime

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.utils import timezone
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView
)
from .models import Post, Comment, Subscription, Notification, Tag, TagType
from .filters import remove_hash
remove_hash
def string_to_bool(str):
    return str and str.lower() in ['true', '1', 'yes']

# def home(request):
#     context = {
#         'posts': Post.objects.all()
#     }
#     return render(request, 'blog/home.html', context)


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/home.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

    def get_queryset(self):
        user = self.request.user
        posts = Post.objects.order_by('-date_posted').all()
        for p in posts:
            p.is_user_subscribed = p.subscriptions.filter(user__id__exact=user.id).exists()
            p.is_user_subscribed_not = not p.is_user_subscribed

        return posts


class PostListView2(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/home2.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

    def get_queryset(self):
        user = self.request.user
        posts = Post.objects.order_by('-date_posted').all()
        for p in posts:
            p.is_user_subscribed = p.subscriptions.filter(user__id__exact=user.id).exists()
            p.is_user_subscribed_not = not p.is_user_subscribed

        return posts


class UserPostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/user_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = self.request.user
        posts = Post.objects.filter(author=user).order_by('-date_posted').all()
        for p in posts:
            p.is_user_subscribed = p.subscriptions.filter(user__id__exact=user.id).exists()
            p.is_user_subscribed_not = not p.is_user_subscribed

        return posts


# region Post - Views


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super(PostDetailView, self).get_object()
        user = self.request.user
        obj.is_user_subscribed = obj.subscriptions.filter(user__id__exact=user.id).exists()
        obj.is_user_subscribed_not = not obj.is_user_subscribed
        return obj


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'anonymous']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'anonymous']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


# endregion

# region Comment - Views
class CommentDetailView(DetailView):
    model = Comment
    # ordering = ['-date_posted']
    template_name = 'blog/comment_detail.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        is_editable = string_to_bool(self.request.GET.get('editable'))
        commentId = self.kwargs['pk']
        obj = Comment.objects.get(id=commentId)

        return {'comment':obj, 'editable': is_editable, 'post':obj.post}

class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['content', 'anonymous']
    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = Post.objects.get(pk=self.kwargs.get('post_id'))
        return super().form_valid(form)


class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    fields = ['content', 'anonymous']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


# class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
#     model = Comment
#     success_url = '/'
#
#     def test_func(self):
#         post = self.get_object()
#         if self.request.user == post.author:
#             return True
#         return False


# endregion


def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})


# region - Subscription

def subscribe_post(request, post_id):
    user = request.user
    post = Post.objects.get(pk=post_id)

    is_already_subscribed = Subscription.objects.filter(user__id__exact=user.id, post__id__exact=post.id).exists()
    if not is_already_subscribed:
        s = Subscription(user=user, post=post)  # Creating Like Object
        s.save()  # saving it to store in database
        is_saved = Subscription.objects.filter(user__id__exact=user.id, post__id__exact=post.id).exists()
    else:
        is_saved = True

    data = {
        'result': is_saved
    }
    return JsonResponse(data)


def unsubscribe_post(request, post_id):
    user = request.user
    post = Post.objects.get(pk=post_id)

    ss = Subscription.objects.filter(user__id__exact=user.id, post__id__exact=post.id)
    ss.delete()
    is_deleted = not Subscription.objects.filter(user__id__exact=user.id, post__id__exact=post.id).exists()

    data = {
        'result': is_deleted
    }
    return JsonResponse(data)
# endregion
#
# def user_notifications_get(request, username):
#     user = request.user
#
#     nn = Notification.objects.filter(subscription__user=user)
#
#     result = []
#     for n in nn:
#         user_notification = {'comment_id': n.comment.id,
#                              'comment_text': n.comment.content,
#                              'username': n.comment.author.username,
#                              'post_title': n.comment.post.title,
#                              'posted_on': n.comment.date_posted}
#         result.append(user_notification)
#
#     data = {'result': result}
#     final = JsonResponse(data, safe=False)
#
#     return final


# region - Tags



def post_tag_save(request, post_id):
    user = request.user
    post = Post.objects.get(pk=post_id)
    choice = request.POST.get('data_item[choice]')
    tag_type = TagType.objects.get(name=choice)

    is_already_tagged = Tag.objects.filter(post__id__exact=post.id, type__name__exact=choice).exists()
    if not is_already_tagged:
        t = Tag(type=tag_type, post=post)  # Creating Like Object
        t.save()  # saving it to store in database
        is_saved = Tag.objects.filter(post__id__exact=post.id, type__name__exact=choice).exists()
    else:
        is_saved = True

    data = {
        'result': is_saved
    }
    return JsonResponse(data)


def tag_delete(request, tag_id):
    t = Tag.objects.get(pk=tag_id)
    t.delete()
    is_deleted = not Tag.objects.filter(pk=tag_id).exists()

    data = {
        'result': is_deleted
    }
    return JsonResponse(data)


class TagPostsTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'blog/tag_posts.html'        # <app>/<model>_<viewtype>.html

    def get_context_data(self, *, object_list=None, **kwargs):
        choices = self.kwargs['tag_choices']

        choices = choices.split('/')

        posts = Post.objects.all()      # 1000
        for choice in choices:          # Financial, #Political
            tags = Tag.objects.filter(type__name__exact='#' + choice).all()
            posts = posts.filter(tags__in=[tt.id for tt in tags]).order_by('-date_posted').all()

        remaining_choices = set()
        for p in posts:
            p.is_user_subscribed = p.subscriptions.filter(user__id__exact=self.request.user.id).exists()
            p.is_user_subscribed_not = not p.is_user_subscribed
            for t in p.tags.all():
                if remove_hash(t.type.name) not in choices:
                    remaining_choices.add(t.type.name)


        page_size = 2
        is_paginated = posts.count() > page_size
        paginator = Paginator(posts, page_size)  # Show 25 contacts per page

        page = 1
        try:
            page = self.request.GET['page']
        except:
            page = 1

        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            posts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            posts = paginator.page(paginator.num_pages)

        return {'filtered_choices': choices,
                'remaining_choices': remaining_choices,
                'posts': posts,
                'page_obj': posts,
                'is_paginated': is_paginated}

# endregion



def comment_save(request, post_id):
    user = request.user
    post = Post.objects.get(pk=post_id)
    content = request.POST.get('data_item[content]')

blog/templates/blog/about.html
{%extends 'blog/base.html' %}
{% block content %}
    
    <h1>About Blog</h1>

   
{% endblock content %}

blog/templates/blog/comment_box.html
<textarea cols="30" rows="5" class="textarea form-control" required="" id="txt_comment_{{ post.id }}" placeholder="Write your comment here">
</textarea>

<div id="div_id_anonymous" class="form-check">
	 <input type="checkbox" name="anonymous" class="checkboxinput form-check-input" id="chk_anonymous_{{ post.id }}" checked="">
	 <label for="id_anonymous" class="form-check-label">
                    Comment as Anonymous User
	 </label> 
</div>
<br>
<a id="a_{{ post.id }}" style="color:blue;" href="javascript:save_comment('{{ post.id }}', '{{ csrf_token }}')">Save</a>
<a style="color:blue;margin-left: 10px;"href="javascript:hide_me('div_comment_box_{{ post.id}}')">Cancel</a>

blog/templates/blog/comment_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Comment</legend>
                <h2>Are you sure you want to delete the comment "{{ object.content }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'user-posts' object.post.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/comment_detail.html
<div id="comment_detail_{{ comment.id }}" class="float-left full-block padding-top-20 border-top" >

<div class="modal fade" id="myModal" >
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Are You Sure?</h4>
{#        <button type="button" class="close" data-dismiss="modal">&times;</button>#}
      </div>


      <div class="modal-footer">
        <button class = "btn btn-warning"  onclick = "javascript:delete_comment('{{ comment.id }}', '{{ csrf_token }}')">Delete</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>

    <div class="small float-left full-block">
        <div class="float-left">
            {% if comment.author == user %}
                <div id = "div_comment_checkbox_{{ post.id }}_{{ comment.id }}"  class="display_False">
                <input type="checkbox"  class="checkboxinput form-check-input" checked="" data-comment-id="{{ comment.id }}">
                </div>
            {% endif %}
            {% if comment.anonymous %}
                <img id="img_comment_profile_{{ comment.id }}" class="rounded-circle comment-img" src="/media/profile_pics/anonymous.png">
                <a id="href_user_comment_{{ comment.id }}" onclick="return false">Anonymous User</a>
            {% else %}
                <img id="img_comment_profile_{{ comment.id }}" class="rounded-circle comment-img" src="{{ comment.author.profile.image.url }}">
                 <a id="href_user_comment_{{ comment.id }}" class="mr-2" href="{% url 'user-posts' comment.author.username %}">{{ comment.author }}</a>
            {% endif %}
         </div>
                <div class="float-right">
                    <small id = "date_{{ comment.id }}"  class="text-muted" style="float:right;">{{ comment.date_posted|date:"F d, Y P" }}</small>
                </div>
    </div>
    {% if comment.author == user and editable == True %}
        <div class="float-left full-block small">
          <div>
            <a href="javascript:hide_me('p_{{ comment.id }}');$('#edit_txt_comment_'+{{comment.id}}).val($('#p_'+{{ comment.id }}).text());show_me('div_edit_comment_box_{{ comment.id}}');">Edit</a>
            <a style="color:#ff0000; margin-left: 10px;" data-toggle="modal" href="#myModal">Delete</a>
            <span id="spinner_comment_edit_{{ comment.id }}" class="margin-left-10" style="display:none" >Processing...</span>
          </div>

        </div>
    {% endif %}


        <p id ='p_{{comment.id}}'  class="small">{{ comment.content }}</p>

        <div id  = "div_edit_comment_box_{{ comment.id}}" class="display_False">
            <textarea cols="30" rows="5" class="textarea form-control" required="" id="edit_txt_comment_{{ comment.id }}">
            </textarea>

            <div id="div_edit_id_anonymous" class="form-check">
	            <input type="checkbox" name="edit_anonymous" class="checkboxinput form-check-input" id="edit_chk_anonymous_{{ comment.id }}" checked="{{ comment.anonymous }}">
	            <label for="id_anonymous" class="form-check-label">
                    Comment as Anonymous User
	            </label>
            </div>

            <a style="color:blue;" href="javascript:edit_comment('{{ comment.id }}', '{{ csrf_token }}');">Save</a>
            <a style="color:blue;margin-left: 10px;" href="javascript:hide_me('div_edit_comment_box_{{ comment.id}}');show_me('p_{{ comment.id }}');">Cancel</a>
    </div>

</div>

blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Add Comment</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Add</button>
            </div>
        </form>
    </div>

{% endblock content %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}


    {% for p in posts %}

        {% include 'blog/post_raw.html' with post=p %}


    {% endfor %}


    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
  {% endblock content %}

blog/templates/blog/home2.html
{% extends "blog/base.html" %}
{% load filters %}
{% block content %}
    <select id="ddl_tag_search2" class="browser-default custom-select" onchange="toggleElement(this, 'btn_tag_search')" style="width:70%">
      <option value="">--Select Tag To Search--</option>
    </select>

    {% for p in posts %}

        {% include 'blog/post_raw.html' with post=p %}


    {% endfor %}

<script>

    $(document).ready(function() {
        $.ajax({
            url: "http://127.0.0.1:8000/api/v1/tagtype/"
        }).then(function (data) {
            $.each(data.objects, function (i, t) {
                tt = t.name.replace("#", "");
                $('#ddl_tag_search2')
                    .append($("<option></option>")
                        .attr("value", tt)
                        .text(t.name));
                $("[id^='tag2_")
                    .append($("<option></option>")
                        .attr("value", t.name)
                        .text(t.name));


        });
        });
    });



    




</script>

  {% endblock content %}

blog/templates/blog/notification.html
<div class="full-block border-top" style="padding:5px 0 5px 0">
    <div class="small full-block">
        {% if notification.comment.anonymous %}
            <img class="rounded-circle notification-img" src="/media/profile_pics/anonymous.png">
            Anonymous User
        {% else %}
            <img class="rounded-circle notification-img" src="{{ notification.comment.author.profile.image.url }}">
            <a class="mr-2" style="margin-right:1px !important;" href="{% url 'user-posts' notification.comment.author.username %}">{{ notification.comment.author }}</a>
        {% endif %}

        {% if notification.type == 'created' %}
            commented
        {% elif notification.type == 'updated' %}
            modified comment
        {% endif %}
        at <small class="text-muted">{{ notification.comment.date_posted|date:"F d, Y P" }}</small>
        on <a class="mr-2" style="margin-right:1px !important;" href="{% url 'post-detail' notification.subscription.post.id %}">{{ notification.subscription.post.title }}</a>
    </div>
</div>

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_list.html
{% for post in posts %}
    {% include 'blog/post_raw.html' with post=post %}
{% endfor %}
{% if is_paginated %}

  {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
  {% endif %}

  {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
      <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
      <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
  {% endif %}

{% endif %}

blog/templates/blog/tag_posts.html
{% extends "blog/base.html" %}
{% load filters %}
{% block content %}
    <h1 class="mb-3"></h1>
    {% for choice in filtered_choices %}
        <a href="/tags/{{ filtered_choices|path_till_index:forloop.counter }}{{ choice|remove_hash }}/posts">#{{ choice }}</a>
        {% if not forloop.last %}>>{% endif %}
    {% endfor %}
    ({{ page_obj.paginator.count }})
    <br>
    Remaining Choices:
    {% for choice in remaining_choices %}
        <a href="/tags/{{ filtered_choices|path }}/{{ choice|remove_hash }}/posts">{{ choice }}</a>{% if not forloop.last %}, {% endif %}
    {% endfor %}
    {% include "blog/post_list.html"  with posts=posts%}
{% endblock content %}

blog/templates/blog/user_notifications.html
{% extends "blog/base.html" %}
{% block content %}
    <h1 class="mb-3">Notifications for {{ user }} </h1>
    {% for n in notifications %}
        {% include "blog/notification.html" with notification=n %}
    {% endfor %}
    <script type="text/javascript">
        $(document).ready(function(){
            $('#div_notifications').hide();
        });
    </script>
{% endblock content %}

blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% include "blog/post_list.html" with posts=posts %}
{% endblock content %}